ALTER TYPE "AdminActionType" ADD VALUE IF NOT EXISTS 'START_CHALLENGE';
ALTER TYPE "AdminActionType" ADD VALUE IF NOT EXISTS 'RESET_CHALLENGE';

ALTER TABLE "GroupSettings"
ADD COLUMN "automationEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "challengeStartedAt" TIMESTAMP(3);
